# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rsvp' do
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rsvp

  target 'rsvp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rsvpTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rsvp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rsvp-tvOS

  

end
